import { Header } from '@/components/header'
import './globals.css'
import { Archivo } from 'next/font/google'

const archivo = Archivo({ subsets: ['latin'] })

export const metadata = {
  title: 'Vexion',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`${archivo.className} bg-[#05050A] text-[#FFFFFF]`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
